dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
addons:
  ssh_know_hosts: $LINODE_S
before_install:
- openssl aes-256-cbc -K $encrypted_c0c2900331de_key -iv $encrypted_c0c2900331de_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $LINODE_S\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa"
  >> ~/.ssh/config
- pip install -U pip
- pip install pipenv
install:
- pipenv update
script:
- pipenv run pelican content
after_success:
- ssh $LINODE_S_USER@$LINODE_S 'cd $PROJECT && git pull && git submodule update
  --init --recursive && pipenv update && pipenv run pelican content'
